### ISSUE TITLE
PPICLF_USER.h: No such file or directory

### ISSUE THREAD

**Issue by iljah** [dpzwick/ppiclF#25]
Trying to compile stokes 2d c++ example in `.../ppiclF/examples/stokes_2d/c++` but getting:
```
.../mpic++ -z muldefs -c test.cpp -I.../ppiclF/source
In file included from test.cpp:5:
.../ppiclF/source/PPICLC.h:1:10: fatal error: PPICLF_USER.h: No such file or directory
 #include "PPICLF_USER.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
```
Adding ` -I ../user_routines` to CFLAGS seemed to fix this.

**Comment by dpzwick** [comment]
Hi @iljah. Thanks for the feedback. I think there must be a misunderstanding when compiling. I would follow the quickstart guide on the documentation website (https://dpzwick.github.io/ppiclF-doc/quickstart.html). ppiclF must be built for each individual case as it says on the website. So the workflow is: 1) copy ppiclf_user.f and PPICLF_USER.h from an example into the source directory and then 2) make.

**Comment by dpzwick** [comment]
I am going to close this issue since I think following the website will solve this issue for you. If it doesn't please comment back here and I will reopen it.

**Comment by iljah** [comment]
Instructions at https://dpzwick.github.io/ppiclF-doc/quickstart/build.html don't work:
```
$ cp examples/stokes_2d/user_source/ppiclf_user.f source/
cp: cannot stat 'examples/stokes_2d/user_source/ppiclf_user.f': No such file or directory
$ cp examples/stokes_2d/user_source/PPICLF_USER.h source/
cp: cannot stat 'examples/stokes_2d/user_source/PPICLF_USER.h': No such file or directory
```

**Comment by dpzwick** [comment]
Sorry about that, that was from a leftover naming convention. The website should be up to date now.
