### ISSUE TITLE
/usr/bin/ld: cannot find -lppiclF

### ISSUE THREAD

**Issue by iljah** [dpzwick/ppiclF#26]
When compiling stokes 2d test I get:
```
...
***************************
*** USER OBJECT SUCCESS ***
***************************
                           
.../mpif77 -z muldefs -I ../user_routines -o test.out test.o -L.../ppiclF/source -lppiclF -lstdc++ 
/usr/bin/ld: cannot find -lppiclF
collect2: error: ld returned 1 exit status
make: *** [Makefile:26: linkObjs] Error 1
```
Looks like library should be added as dependency so that it's compiled automatically. Or user could also be told to install/compile the library first...

**Comment by dpzwick** [comment]
I think this too is the same issue as here: https://github.com/dpzwick/ppiclF/issues/25.

**Comment by dpzwick** [comment]
I am going to close this issue since I think following the website will solve this issue for you. If it doesn't please comment back here and I will reopen it.
