### ISSUE TITLE
gslib uses hard-coded mpi c++ compiler

### ISSUE THREAD

**Issue by iljah** [dpzwick/ppiclF#27]
I have several MPI compilers installed and none are in default path so installation of gslib fails:
```
gslib]$ ./install 
+ make -j4 DESTDIR=.. ADDUS= USREXIT=0 BLAS=2 PREFIX=gslib_ FPREFIX=fgslib_
mpicc -O2 -I./src  -DMPI -DUNDERSCORE -DGLOBAL_LONG_LONG -DPREFIX=gslib_ -DFPREFIX=fgslib_ -c src/gs.c -o src/gs.o
make: mpicc: Komentoa ei löytynyt
make: *** [Makefile:130: src/gs.o] Virhe 127
```
Is it possible to customize mpi c++ compiler path when installing gslib through ppiclF?

**Comment by dpzwick** [comment]
Thanks for the feedback @iljah. I made the gslib install with the same compilers as the main Makefile so it isn't hard-coded anymore. Although currently ppiclF is only support mpicc (C compiler) and mpif77/mpif90 (Fortran comilers).

**Comment by iljah** [comment]
Thanks but mpicc isn't always the name of mpi c compiler. For example Cray machines have had something like cc as mpi c, CC as mpi c++ and ftn as fortran compiler name for decades. GNU autotools also allow folks to specify executable paths and names with environment variables. Please allow folks to specify full path to compilers.

Also, mpicc is just a wrapper so you can't make any assumptions about what compiler is run by executing mpicc, thus only allowing mpicc as executable name doesn't make sense to me.

**Comment by dpzwick** [comment]
I agree that may be the case. I have reopened the issue and will issue a commit to this issue.
