### ISSUE TITLE
No rule to make target 'source/ppiclf_user.f'

### ISSUE THREAD

**Issue by iljah** [dpzwick/ppiclF#28]
Trying to compile the library gives:
```
$ make
cd ./3rd_party/gslib; \
./install
                       
***********************
*** INSTALLED GSLIB ***
***********************
                       
make: *** No rule to make target 'source/ppiclf_user.f', needed by 'getObjs'. Seis.
```
Am I supposed to create ppiclf_user.f?

**Comment by dpzwick** [comment]
This is the same issue as here: https://github.com/dpzwick/ppiclF/issues/25.

**Comment by dpzwick** [comment]
I am going to close this issue since I think following the website will solve this issue for you. If it doesn't please comment back here and I will reopen it.
