### ISSUE TITLE
relocation truncated to fit..

### ISSUE THREAD

**Issue by tzahtila** [dpzwick/ppiclF#38]
Hi,

I am trying to adapt the  Examples/Nek5000  in ppiclf to Nek5000/examples/NekExamples/turbChannel in Nek5000. 

Presently, I am trying to copy the usrdat2 code from the former to the latter.

If I uncomment this block of code, 

`      call ppiclf_comm_InitMPI(nekcomm,
     >                         nid    , ! nid already defined in Nek5000
     >                         np     ) ! np already defined in Nek5000`

I get the following error that I cannot make sense of. 

`/home/zd/ppiclF/source/libppiclF.a(ppiclf.o): In function `ppiclf_io_writesubbinvtu_':
ppiclf.f:(.text+0xcf40): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0xcf9f): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0xd112): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0xd433): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0xd4d2): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0xea91): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0xeb28): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0xeb87): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0xf86f): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0xfc11): relocation truncated to fit: R_X86_64_PC32 against symbol `ppiclf_opt_param_i_' defined in COMMON section in /home/zd/ppiclF/source/libppiclF.a(ppiclf.o)
ppiclf.f:(.text+0x10405): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status`

Any help appreciated.

**Comment by tzahtila** [comment]
Some additional information: 
-If I toggle the ldim = 2 or 3 in the SIZE file, it will compile succesfully for 2D but not 3D.

**Comment by tzahtila** [comment]
Hey David, sorry to be a pain. 

I have remedied this by increasing the minimum number of MPI ranks.

**Comment by dpzwick** [comment]
@tzahtila I'm glad to hear this is working for you now. Sorry it took so long for me to see this. Usually the relocation compiler errors are due to not having enough memory as you found. One way you can decrease this regarding particles is by setting PPICLF_LPART in the H File to be smaller than its default value which is usually really large. I've found personally that going higher than even 5000 or so isn't necessary most of the time.
